swagger: '2.0'
info:
  title: DreamBoard Backend Endpoint
  description: Dreamboard API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
host: {CLOUD_RUN_HOST_NAME}
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: {CLOUD_RUN_SERVICE_URL}
  protocol: h2
paths:
  /video_health_check:
    post:
      summary: Health check for video routes
      operationId: video_health_check
      responses:
        '200':
          description: A successful response
          schema:
            type: object
  /image_health_check:
    get:
      summary: Health check for image routes
      operationId: image_health_check
      responses:
        '200':
          description: A successful response
          schema:
            type: object
  /text_health_check:
    get:
      summary: Health check for text routes
      operationId: text_health_check
      responses:
        '200':
          description: A successful response
          schema:
            type: object